[FIR] Reproduce ^KT-71943
Note that these two runners fail:

- `LLFirPreresolvedReversedDiagnosticCompilerFE10TestDataTestGenerated`
- `DiagnosticCompilerTestFE10TestdataTestGenerated`

...with:

> Fail file exists but no exception was thrown. Please remove nullSourceInJvmModuleChecker.fir.fail
> java.lang.AssertionError: Fail file exists but no exception was thrown. Please remove nullSourceInJvmModuleChecker.fir.fail

And cannot be disabled by:

```
// IGNORE_NON_REVERSED_RESOLVE
// IGNORE_REVERSED_RESOLVE
```

...because otherwise they complain that there're no errors and the
directives must be removed.

Also, it's important that the test resides in this folder. This is due
to the fact that `findJavaModule()` from `CliJavaModuleResolver.kt`
makes a check for:

```
file.fileSystem.protocol == StandardFileSystems.JRT_PROTOCOL
```

...and for regular tests we'd see here `FastJarFileSystem`, not
`CoreJrtFileSystem` and thus fail it, and also we need to make sure:

```
val jdkHome = configuration.get(JVMConfigurationKeys.JDK_HOME)
val releaseTarget = configuration.get(JVMConfigurationKeys.JDK_RELEASE)
```

...are set in `KotlinCoreEnvironment.kt`, which doesn't happen for
tests not targeting a specific JDK in our infrastructure. Otherwise,
`CliJavaModuleResolver.kt` would have no knowledge about java modules
and thus won't match the check that actually happens in the wild.