~ stub tests
DecompiledKnmStubConsistencyK2TestGenerated

Though the exception below fails only because stubs are not built properly

java.lang.IllegalStateException: @NotNull method com/intellij/openapi/application/AsyncExecutionService.getService must not return null
  at com.intellij.openapi.application.AsyncExecutionService.$$$reportNull$$$0(AsyncExecutionService.java)
  at com.intellij.openapi.application.AsyncExecutionService.getService(AsyncExecutionService.java:31)
  at com.intellij.openapi.application.AppUIExecutor.onWriteThread(AppUIExecutor.java:41)
  at com.intellij.psi.impl.source.PsiFileImpl.rebuildStub(PsiFileImpl.java:1098)
  at com.intellij.psi.impl.source.FileTrees.reconcilePsi(FileTrees.java:199)
  at com.intellij.psi.impl.source.FileTrees.withStub(FileTrees.java:148)
  at com.intellij.psi.impl.source.PsiFileImpl.calcStubTree(PsiFileImpl.java:1086)
  at org.jetbrains.kotlin.analysis.decompiler.konan.AbstractDecompiledKnmStubConsistencyTest.checkKnmStubConsistency(AbstractDecompiledKnmStubConsistencyTest.kt:61)
  at org.jetbrains.kotlin.analysis.decompiler.konan.AbstractDecompiledKnmStubConsistencyTest.doTest(AbstractDecompiledKnmStubConsistencyTest.kt:37)
  at org.jetbrains.kotlin.analysis.decompiler.konan.AbstractDecompiledKnmFileTest.runTest$lambda$0(AbstractDecompiledKnmFileTest.kt:58)
  at org.jetbrains.kotlin.analysis.decompiler.konan.AbstractDecompiledKnmFileTest.withKnmIgnoreDirective(AbstractDecompiledKnmFileTest.kt:117)
  at org.jetbrains.kotlin.analysis.decompiler.konan.AbstractDecompiledKnmFileTest.runTest(AbstractDecompiledKnmFileTest.kt:58)
  at org.jetbrains.kotlin.analysis.decompiler.konan.DecompiledKnmStubConsistencyK2TestGenerated.testAnnotatedParameterInEnumConstructor(DecompiledKnmStubConsistencyK2TestGenerated.java:35)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at junit.framework.TestCase.runTest(TestCase.java:177)
  at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.lambda$runTest$5(KtUsefulTestCase.java:265)
  at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.invokeTestRunnable(KtUsefulTestCase.java:292)
  at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.runTest(KtUsefulTestCase.java:280)
  at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.defaultRunBare(KtUsefulTestCase.java:303)
  at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.runBare(KtUsefulTestCase.java:364)