[Wasm] Fix 'wasmInst0cache' failing with CCE
^KT-89445 fixed

The following StackTrace was captured in unrelated CI builds:

    java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
      at java.base/java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1900)
      at java.base/java.util.HashMap$TreeNode.treeify(HashMap.java:2016)
      at java.base/java.util.HashMap.treeifyBin(HashMap.java:768)
      at java.base/java.util.HashMap.putVal(HashMap.java:640)
      at java.base/java.util.HashMap.put(HashMap.java:608)
      at org.jetbrains.kotlin.wasm.ir.WasmInstructionKt.wasmInstrWithoutLocation(WasmInstruction.kt:199)
      at org.jetbrains.kotlin.wasm.ir.WasmInstructionKt.wasmInstrWithLocation(WasmInstruction.kt:114)
      at org.jetbrains.kotlin.wasm.ir.WasmExpressionBuilder.buildInstr(WasmExpressionBuilder.kt:67)
      at org.jetbrains.kotlin.backend.wasm.ir2wasm.BodyGenerator.tryToGenerateWasmOpIntrinsicCall(BodyGenerator.kt:1856)
      at org.jetbrains.kotlin.backend.wasm.ir2wasm.BodyGenerator.tryToGenerateIntrinsicCall(BodyGenerator.kt:1117)
      at org.jetbrains.kotlin.backend.wasm.ir2wasm.BodyGenerator.generateCall(BodyGenerator.kt:893)
      at org.jetbrains.kotlin.backend.wasm.ir2wasm.BodyGenerator.visitCall(BodyGenerator.kt:689)
      at org.jetbrains.kotlin.ir.visitors.IrVisitorVoid.visitCall(IrVisitorVoid.kt:364)
      at org.jetbrains.kotlin.ir.visitors.IrVisitorVoid.visitCall(IrVisitorVoid.kt:18)
      at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:24)
      at org.jetbrains.kotlin.ir.visitors.IrVisitorsKt.acceptVoid(IrVisitors.kt:11)

The underlying code

```kotlin
private val wasmInst0cache = mutableMapOf<WasmOp, WasmInstr0>()
fun wasmInstrWithoutLocation(operator: WasmOp): WasmInstr =
    wasmInst0cache.getOrPut(operator) { WasmInstr0(operator) }
```

has no visible issues, other than it not being Thread safe.

This commit will pre-populate the cache during ClassLoading
instead of populating the cache lazily, taking leverage of the fact
that the instruction enum is finite and reasonably sized.