Bump JDK 8 in Jakarta tests to 17
See: `FirPsiOldFrontendForeignAnnotationsCompiledJavaTestGenerated.testDefault`,
which is now failing with:

```
error: cannot access TypeQualifierNickname
import javax.annotation.meta.TypeQualifierNickname;
                            ^
  bad class file: /private/var/folders/5r/wwlpp6t51j3910jcq7298jx40000kt/T/analysis-testsProject_test_1087416050040299649/testLibrary-jsr305/jsr305.jar(/javax/annotation/meta/TypeQualifierNickname.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```