[kotlin compiler][update] 1.3.50-dev-1913
* 37002748c84 - (tag: build-1.3.50-dev-1913) Do not wrap and display cause's message in compiler exceptions (3 дня назад) <Alexander Udalov>
* 430aed65592 - (tag: build-1.3.50-dev-1909) Minor: clean up code (3 дня назад) <Dmitry Gridin>
* 1f89c0f7302 - "Convert to sealed class" intention: don't suggest when no "class" keyword (3 дня назад) <Toshiaki Kameyama>
* 9786564d75f - (tag: build-1.3.50-dev-1908) "Remove argument name" intention: remove array literal brackets for annotation vararg argument (3 дня назад) <Toshiaki Kameyama>
* d33d1913cbf - (tag: build-1.3.50-dev-1907, tag: build-1.3.50-dev-1904) Not throw exception when cidr has been registered already (3 дня назад) <Juan Chen>
* 9f6e88d5713 - Formatter: format around safe cast operator `as?` (KT-32324) (3 дня назад) <Toshiaki Kameyama>
* 44e9090931b - Formatter: format between type reference and 'by' keyword (KT-32277) (3 дня назад) <Toshiaki Kameyama>
* 0b8f35c04d3 - (tag: build-1.3.50-dev-1896) Revert "Register mock injection language manager in compiler" (3 дня назад) <Nikolay Krasko>
* f9b53da0fa8 - (tag: build-1.3.50-dev-1895) Attempt to fix some inspection tests (3 дня назад) <Dmitry Gridin>
* 8a569cc6986 - (tag: build-1.3.50-dev-1888) [JS IR BE] Do not create `$default` stub for external function and any its fake override (4 дня назад) <Roman Artemev>
* 28a108a2054 - [JS IR BE] Visit callable reference members in private member lowering (4 дня назад) <Roman Artemev>
* b4c68025a7a - [JS IR BE] Improve error reporting (4 дня назад) <Roman Artemev>
* 940c9e56042 - (tag: build-1.3.50-dev-1885) 192: build against IDEA 192.5587.17 (4 дня назад) <Vyacheslav Karpukhin>
* a2625c7bc85 - (tag: build-1.3.50-dev-1882) [JS IR BE] Don't render null messages in Throwable (4 дня назад) <Svyatoslav Kuzmich>
* 94aebd01012 - (tag: build-1.3.50-dev-1880) [JS IR BE] Proper support for String and Any constructors (4 дня назад) <Svyatoslav Kuzmich>
* d7cb3e05ef3 - (tag: build-1.3.50-dev-1878, origin/rr/romart/cityhash_js) [JS IR BE] Replace 32bit default String.hashcode with 64bit cityhash for UniqID  Split uniqID space into two part 63 bit each. (4 дня назад) <Roman Artemev>
* 46eb929bd1c - (tag: build-1.3.50-dev-1872) ControlFlowWithEmptyBodyInspection: shouldn't report on `while` with comments  #KT-32419 Fixed (4 дня назад) <Dmitry Gridin>
* 6e750b08570 - (tag: build-1.3.50-dev-1869) Enable API watcher in Kotlin (4 дня назад) <Nikolay Krasko>
* ef903538318 - Another test-runtime java plugin dependency (4 дня назад) <Nikolay Krasko>
* 5d081efe605 - (tag: build-1.3.50-dev-1867) Uast: tests for no implicit returns in lambdas (KT-32370) (4 дня назад) <Nicolay Mitropolsky>
* a180d78eaf1 - Uast: implicit returns for local function bodies (KT-32370) (4 дня назад) <Nicolay Mitropolsky>
* f85ebe7f43b - Uast: implicit returns for lambda expressions (KT-32370) (4 дня назад) <Nicolay Mitropolsky>
* 631a09e5412 - (tag: build-1.3.50-dev-1859) [JS IR BE] ThrowableLowering: Use dynamic operators instead of jsSetJSField intrinsic (5 дней назад) <Svyatoslav Kuzmich>
* 871180cdc0b - [JS IR BE] Fix setting names of Throwable subclasses without primary constructor (5 дней назад) <Svyatoslav Kuzmich>
* 918d470e1be - [JS IR BE] Simplify throwable lowering. (5 дней назад) <Svyatoslav Kuzmich>
* 6d1f893a5aa - [JS IR BE] Move object instance creation lowerings to IR (5 дней назад) <Svyatoslav Kuzmich>
* 5dcb0ee016d - [JS IR BE] Reduce JsScope usage in codegen (5 дней назад) <Svyatoslav Kuzmich>
* a9c8fd903b6 - reduce calls to Object.hashCode originating from LabelNormailizationMethodTransformer (5 дней назад) <Jeffrey van Gogh>
* 361c468c339 - (tag: build-1.3.50-dev-1857) IR: move type utilities from IrTypeUtils.kt to irTypePredicates.kt (5 дней назад) <Alexander Udalov>
* 7c6f48df39f - (tag: build-1.3.50-dev-1854, tag: build-1.3.50-dev-1841, tag: build-1.3.50-dev-1831) Revert "Set sourceCompatibility and targetCompatibility for JavaCompile tasks" (5 дней назад) <Alexey Tsvetkov>
* 2a3bb2968e2 - Revert "Call configureJvmProject once per project in afterEvaluate" (5 дней назад) <Alexey Tsvetkov>
* ab6174defd2 - Revert "Check JDK env vars once during configuration when not syncing" (5 дней назад) <Alexey Tsvetkov>
* aa7aff84fc6 - Revert "Do not fork java compile tasks when current JDK can be used" (5 дней назад) <Alexey Tsvetkov>
* 9340bffd02a - (tag: build-1.3.50-dev-1829) Revert "Add ext.jvmTarget and ext.javaHome to core:descriptors.runtime" (5 дней назад) <Alexey Tsvetkov>
* 1a290621b07 - (tag: build-1.3.50-dev-1825) Minor. Update multiplatform kotlin plugin version in HMPP tests (5 дней назад) <Andrey Uskov>
* e079615cdf7 - (tag: build-1.3.50-dev-1816) Add possibility to edit target platform for non-HMPP projects in order to keep ability to edit target platform for IDEA-based projects (6 дней назад) <Andrey Uskov>
* efb0e692ae1 - Minor. Reformat KotlinFacetEditorGeneralTab (6 дней назад) <Andrey Uskov>
* 9fc60be9d83 - Fix serialization of facet settings in order to read properly settings of native platforms (6 дней назад) <Andrey Uskov>
* 404ce1a8c1d - Facet serialization changed in order to keep compatibility with previous versions of Kotlin plugin (6 дней назад) <Andrey Uskov>
* 87e75bd4cc0 - HMPP: fix importing target platforms for case when JVM targets are involved (6 дней назад) <Andrey Uskov>
* 8445e3a2a4b - HMPP: add importing tests (6 дней назад) <Andrey Uskov>
* 8280c647af4 - HMPP: Migration of source root types for middle HMPP source sets fixed (6 дней назад) <Andrey Uskov>
* 90187c959ed - Add test for 'isHMPP' flag (6 дней назад) <Andrey Uskov>
* e791b9d3f75 - HMPP: import flag indicating that the project uses HMPP feature (6 дней назад) <Andrey Uskov>
* 35dea296fa2 - Add ext.jvmTarget and ext.javaHome to core:descriptors.runtime (6 дней назад) <Alexey Tsvetkov>
* d3f9d0866ac - (tag: build-1.3.50-dev-1803, tag: build-1.3.50-dev-1800, tag: build-1.3.50-dev-1797, tag: build-1.3.50-dev-1790) Build: Improve cache redirector usage in buildSrc settings.gradle (6 дней назад) <Vyacheslav Gerasimov>
* 8b05d4df46c - (tag: build-1.3.50-dev-1787) More NoClassDefFoundError fixes in tests after 192 update (6 дней назад) <Nikolay Krasko>
* ba64600ee5c - (tag: build-1.3.50-dev-1784) Gradle: Make K/N properties uniform with other Kotlin properties (6 дней назад) <Ilya Matveev>
* fd1fc7d28a5 - Gradle: Support K/N restricted distribution (6 дней назад) <Ilya Matveev>
* 35d7fff0354 - Gradle: Fix input annotation for the Webpack task (6 дней назад) <Ilya Matveev>
* f2021b580e5 - (tag: build-1.3.50-dev-1782) Do not fork java compile tasks when current JDK can be used (6 дней назад) <Alexey Tsvetkov>
* 48b86bba691 - Check JDK env vars once during configuration when not syncing (6 дней назад) <Alexey Tsvetkov>
* 33de71f7920 - Call configureJvmProject once per project in afterEvaluate (6 дней назад) <Alexey Tsvetkov>
* 290aded94f7 - Set sourceCompatibility and targetCompatibility for JavaCompile tasks (6 дней назад) <Alexey Tsvetkov>
* f8035096ea6 - (tag: build-1.3.50-dev-1781) JS: lock tape version to avoid kotlin.test + tape integration test failure (6 дней назад) <Anton Bannykh>
* 60ac2056bdc - (tag: build-1.3.50-dev-1780, tag: build-1.3.50-dev-1777) Update diagnostic message in test data (6 дней назад) <Mikhail Zarechenskiy>
* a67c3ef855e - Update 183 branch to 183.6156.11 (6 дней назад) <Nikolay Krasko>
* 2d85d18a74b - Minor: add more exceptions to project dictionary (6 дней назад) <Nikolay Krasko>
* 28a45909a0f - Fix compatibility with 192 branch (KT-32364) (6 дней назад) <Nikolay Krasko>
* ba2ca5ae3cc - Fallback to simple oocb when per-language trackers are disabled (KT-32364) (6 дней назад) <Nikolay Krasko>
* f605d4e73b6 - Revise per module out-of-code-block (KT-32364) (6 дней назад) <Nikolay Krasko>
* 73eea6f4b6a - Minor: rename file before refactoring (6 дней назад) <Nikolay Krasko>
* 4f678c82892 - Create project service with Kotlin trackers (KT-32364) (6 дней назад) <Nikolay Krasko>
* 263d8eea16e - Use Kotlin oocb instead of platform oocb tracker (KT-32364) (6 дней назад) <Nikolay Krasko>
* 557ea54a9ff - Introduce Kotlin specific out-of-code-block tracker (KT-32364) (6 дней назад) <Nikolay Krasko>
* 12bb1a5bd12 - Make invalidateOnOOCB explicit in ResolverForProjectImpl and remove usage in tests (6 дней назад) <Nikolay Krasko>
* b32b3628105 - Extract KotlinModuleModificationTracker to separate file (6 дней назад) <Nikolay Krasko>
* 26c7eddb036 - Move trackers to caches.trackers package (6 дней назад) <Nikolay Krasko>
* 2ddcd9f0af9 - Minor: cleanup and reformat KotlinCodeBlockModificationListener.kt (6 дней назад) <Nikolay Krasko>
* 2029d16062f - (tag: build-1.3.50-dev-1776, tag: build-1.3.50-dev-1773) Add add-imports performance tests Add missed auto generated perf tests (6 дней назад) <Vladimir Dolzhenko>
* 57a732c247c - (tag: build-1.3.50-dev-1769) Minor: fixes after review (6 дней назад) <Dmitry Gridin>
* 9316f45a5c2 - Optimize Imports: improve tooltip information  #KT-21374 Fixed (6 дней назад) <Dmitry Gridin>
* 074829bcead - Import: IDE should import class from root package  #KT-21422 Fixed (6 дней назад) <Dmitry Gridin>
* 148eed2a12c - ShortenReferences: fix false negative for object call chain #KT-32320 Fixed (6 дней назад) <Dmitry Gridin>
* 33914a3a946 - ImportMemberIntention: make more flexible based on caret position  #KT-31924 Fixed (6 дней назад) <Dmitry Gridin>
* 6f2f60869c3 - (tag: build-1.3.50-dev-1767) Minor: Don't create unnecessary PluginId instances (6 дней назад) <Dmitriy Dolovov>
* 208c8f93397 - (tag: build-1.3.50-dev-1759, origin/4u7/compare-dist) JS: fix bootstrap (7 дней назад) <Anton Bannykh>
* 69962cbf8ce - (tag: build-1.3.50-dev-1756) [JS IR BE] Add JsExport annotations (7 дней назад) <Svyatoslav Kuzmich>
* 685597d20a9 - [JS IR BE] Codegen class model refactorings (7 дней назад) <Svyatoslav Kuzmich>
* e7a5e5b4a05 - (tag: build-1.3.50-dev-1748) JVM_IR: Handle annotation KClass fields in external declarations (7 дней назад) <Steven Schäfer>
* 1ab0b76af3b - (tag: build-1.3.50-dev-1747) Minor: use more descriptive argument name (7 дней назад) <Steven Schäfer>
* 078ccbf0778 - JVM_IR: Implement name mangling exceptions for Result class. (7 дней назад) <Steven Schäfer>
* d458e4a7b24 - JVM_IR: Enable inlining for external declarations with inline class parameters. (7 дней назад) <Steven Schäfer>
* da86ef8454e - (tag: build-1.3.50-dev-1746, origin/selezneva/forpush) Fix tests for long command line: create folder instead of file (7 дней назад) <Natalia Selezneva>
* 30222582f48 - Scratch tests: print test output at onFinish to avoid multiple calls of invokeLater (7 дней назад) <Natalia Selezneva>
* 85f07927c9a - Minor: check output with errors in scratch tests (7 дней назад) <Natalia Selezneva>
* 784cc17d21c - Do not use deprecated UIUtil.invokeLaterIfNeeded. Use TransactionGuard instead (7 дней назад) <Natalia Selezneva>
* 63246f57d2b - Scripts: drop sdk caches on project root change event (7 дней назад) <Natalia Selezneva>
* d981135c4bf - Scratch: finish execution if no new lines was executed (7 дней назад) <Natalia Selezneva>
* 7ef9fb5511f - (tag: build-1.3.50-dev-1743) Export deserialization constructor from JS module (7 дней назад) <Leonid Startsev>