[FIR] Commit reasonable test data changes
`output.txt` seems reasonable, because this way it's obvious why the
compiler considers the expanded type empty.

`TypeAlias.fir.txt` used by a byproduct of how the serialization worked
previously (incorrectly). Also, the test infrastructure is misconfigured
there, as the test difference fails with:

> org.opentest4j.FileInfojava.lang.NoClassDefFoundError:
> org/opentest4j/FileInfo

`usage.kt` looks like an improvement (now the K2 file seems to differ
less from the K1 one).