[213] Add library dependencies to kotlin-native.jar
While dependency is added to backend.native, it's than
transitively packed to :kotlin-native:shadowJar. Without it
running gradle with -Pkotlin.native.useEmbeddableCompilerJar=false fails
with

e: java.lang.NoClassDefFoundError: org/codehaus/stax2/typed/TypedXMLStreamException

KTI-1114