[Build] Fix class circularity in test-inputs-check-v2 for JDK >= 24
KTI-3068

The issue happens when executing tests on JDK >= 24.

It can manifest itself in different ways, depending on which instrumentations are installed. One of such cases is described below.

Simplified stack trace:
```
java.lang.ClassCircularityError: sun.nio.ch.FileChannelImpl
	at sun.nio.fs.UnixChannelFactory.newFileChannel()
	...
	at java.nio.file.Files.newBufferedReader()
	at org.jetbrains.kotlin.testFramework.inputchecking.UndeclaredInputsGuard.initialize()
	at java.io.RandomAccessFile.read()
	...
	at java.lang.ClassLoader.loadClass()
	at net.bytebuddy.pool.TypePool$Empty.describe()
	...
	at net.bytebuddy.ByteBuddy.decorate()
	...
	at net.bytebuddy.ExecutingTransformer.transform(): Failed transformation of sun.nio.ch.FileChannelImpl
```

Explanation:
- it happens due to clash between instrumenting `RandomAccessFile` and `FileChannelImpl`
- the `RandomAccessFile` is instrumented first, everything is ok at this point
- then ByteBuddy tries to instrument  `FileChannelImpl` -> its internal implementation uses `RandomAccessFile` (which is already instrumented)
- `RandomAccessFile` delegates to `UndeclaredInputsGuard` which delegates to `FileChannelImpl` which is currently being modified by ByteBuddy...
- JVM throws `ClassCircularityError`

To fix this issue, we initialize `UndeclaredInputsGuard` eagerly, not lazily on its first usage.