Fix Spring tests failure for 192 branch (KT-33803)
Remove kotlin-compiler from ultimate idea dependencies. It has a
proguarded version of idea classes that once found in classpath before
original versions ruins tests.

This time the reason was: Caused by: java.lang.NoSuchMethodError: com.intellij.openapi.roots.impl.LanguageLevelProjectExtensionImpl.setDefault(Ljava/lang/Boolean;)V

Rearrange other dependencies.