Bump JDK 8 in Java Direct tests to 17
See: `JavaUsingAstPhasedTestGenerated.testPseudoRawTypes`, which is now
failing with:

```
java.lang.IllegalArgumentException: invalid flag: --patch-module
```