ReadMe > Build environment requirements fix
JDK 6 setup for MacOS is outdated.
Brew `caskroom/versions` was moved. Now it's available via `homebrew/cask-versions`.

Now user is getting error setting up build env:
> Error: caskroom/versions was moved. Tap homebrew/cask-versions instead.