[K/N] Add toString in DeserializedSourceFile
DeserializedSourceFile::toString() gets called when reporting ObjCExport
name clashes, e.g.

error: name "FooBarBazKt" is mangled when generating Objective-C header because it conflicts with org.jetbrains.kotlin.library.metadata.DeserializedSourceFile@fc2da742

This fix adds a more meaningful toString.