Run analysis-tests with JDK 17 instead of 8 by default
See: `PhasedJvmDiagnosticLightTreeTestGenerated.testPseudoRawTypes`,
which is now failing with:

```
java.lang.IllegalArgumentException: invalid flag: --patch-module
```