Show raw java compiler output if no diagnostic collected
Sometimes there are no diagnostics, so it's not clear what has caused
errors.

Found while playing with a Security manager. Additional logging helped
 to reveal the issues:

An exception has occurred in the compiler (1.8.0_432). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.security.AccessControlException: access denied ("java.io.FilePermission" "~/Library/Java/Extensions" "read")


Merge-request: KT-MR-21164
Merged-by: Nikolay Krasko <Nikolay.Krasko@jetbrains.com>