CIDR: Fix exceptions due to partially available KotlinDslScript model
For example:
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:548)
	at org.jetbrains.kotlin.idea.scripting.gradle.importing.KotlinDslSyncListener$Companion.getInstance(KotlinDslSyncListener.kt:28)
	at org.jetbrains.kotlin.idea.scripting.gradle.importing.KotlinDslScriptModelProcessorKt.saveGradleBuildEnvironment(KotlinDslScriptModelProcessor.kt:25)
	at org.jetbrains.kotlin.idea.scripting.gradle.importing.KotlinDslScriptModelContributor$accept$1.accept(KotlinDslScriptModelResolver.kt:49)
	at org.jetbrains.kotlin.idea.scripting.gradle.importing.KotlinDslScriptModelContributor$accept$1.accept(KotlinDslScriptModelResolver.kt:33)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.jetbrains.kotlin.idea.scripting.gradle.importing.KotlinDslScriptModelContributor.accept(KotlinDslScriptModelResolver.kt:39)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.lambda$doResolveProjectInfo$2(GradleProjectResolver.java:298)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.java:33)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.java:49)
	at org.jetbrains.plugins.gradle.service.project.GradleProjectResolver.doResolveProjectInfo(GradleProjectResolver.java:295)