KT-12895, EA-84877: Fix NoSuchMethodError thrown when saving a Kotlin file. newOutputStreamSupplier() is deprecated and was deleted in Guava 18. (cherry picked from commit bb083a5)