Properly construct `--patch-module` options for `javac` in tests
See: `PhasedJvmDiagnosticLightTreeTestGenerated.testPseudoRawTypes`,
which otherwise fails with:

```
error: package exists in another module: java.base
package java.util;
^
/private/var/folders/5r/wwlpp6t51j3910jcq7298jx40000kt/T/analysis-testsProject_test_13609197263127965719/org.jetbrains.kotlin.test.runners.PhasedJvmDiagnosticLightTreeTestGenerated_Tests_GenericstestPseudoRawTypes/java-sources/main/test/Usage.java:16: error: cannot find symbol
    c.foo();
     ^
  symbol:   method foo()
  location: variable c of type java.util.Collection
```

In modern Java, it's no longer possible to "overload" the stdlib classes
like it was in 9 - we need an explicit option to enable that.

Another nice test: `PhasedJvmDiagnosticPsiTestGenerated.testClassFromJdkInLibrary`.