[202] Fix `java.lang.IncompatibleClassChangeError` after platform update
This commit fixes `KotlinUastApiTest` (and other Kotlin UAST tests) in current infrastructure
for 202 platform. These tests were broken after 202 platform update by previous commit:
```
java.lang.IncompatibleClassChangeError: Expected static field com.intellij.psi.compiled.ClassFileDecompilers.EP_NAME
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreApplicationEnvironment.registerExtensionPoints(KotlinCoreApplicationEnvironment.java:43)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreApplicationEnvironment.create(KotlinCoreApplicationEnvironment.java:26)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createApplicationEnvironment(KotlinCoreEnvironment.kt:506)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForTests(KotlinCoreEnvironment.kt:451)
```