[stdlib] Introduce kotlin.NoClassDefFoundError on non-JVM targets
This exception should be thrown whenever we access a class whose
initialization has previously failed with `ExceptionInInitializerError`.
This makes the behavior closer to what happens on JVM.

^KT-57134 Fixed