Catch NoClassDefFoundError when BuildScanExtension is not found
Add simple test with init script

#KT-59589

(cherry picked from commit 27043bd8a6dd2a03017c4dcf2f7d68a68ce29706)