Relocate aalto-xml and stax2-api dependencies in embeddable compiler (KT-59631)
Two additional dependencies were added during 213 platform migration:
com.fasterxml:aalto-xml
org.codehaus.woodstox:stax2-api

Packages were not relocated and now might cause failures such as

```
Caused by: java.lang.NoSuchMethodError: 'void com.fasterxml.aalto.in.ReaderConfig.setXMLResolver(javax.xml.stream.XMLResolver)'
```

if proguard classes of kotlin-compiler-embeddable are registered early
in the classpath.

(cherry picked from commit d4c8636c70e7ae9138b1457e1d863c645752e9ef)