Fix a leak in `:compiler:incremental-compilation-impl:test`
`PreciseJavaInteropCoordinator` instantiates a new `rootDisposable`
each time, but it's never disposed after the analysis has finished,
resulting in a leak.

Co-authored-by: Claude Code

NB: There seems to be somewhere another issue with running `:test` with
no filters, that causes `ClassesFqNamesTest` to sometimes fail with
something like:

```
org.opentest4j.AssertionFailedError: expected: <test.A
test.C
test.E
test.I
test.O> but was: <>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
	at org.jetbrains.kotlin.incremental.parsing.ClassesFqNamesTest.doTest(ClassesFqNamesTest.kt:138)
	at org.jetbrains.kotlin.incremental.parsing.ClassesFqNamesTest.testDifferentTypeOfClasses(ClassesFqNamesTest.kt:56)
```

Sometimes, `virtualFile.fileType` of `kotlinFiles` inside `classesFqNames`
is `EmptyFileTypeRegistry$EmptyLanguageFileType`.

It seems this fix for `rootDisposable` helps to avoid/hide this issue
somehow, and another one is necessary, but I haven't investigated it
further.

(cherry picked from commit d4eab1e63ebd1e4e23466fd406ee3488adcec45e)