Fix NoSuchMethodError when try to access in test to internal member from production for gradle projects imported into IDEA 16 or higher
 #KT-11993 Fixed
(cherry picked from commit ed0fa2c)