[FIR] Expand typealiases in supertypes
These are the tests that were broken initially by the absense of the
typealias in supertypes expansion.

In `withAbbreviation` it's important to replace the attribute if exists:
consider types obtained via `typealias -> typealias -> class`. They must
contain the first typealias as the abbreviated type. For an example, see:
`FirPsiOldFrontendDiagnosticsTestGenerated.testKt15734`, where
`REDUNDANT_NULLABLE` disappears if the attribute is not replaced.

Checking `expandedTypeRef` is not enough to get the typealias expansion,
because the expanded type may have not yet been applied. See:
`FirPsiDiagnosticTestGenerated.testStatusResolveForTypealiasAsSuperClass`,
where `NOTHING_TO_OVERRIDE` appears otherwise.

Checking `FirImplicitBuiltinTypeRef` is needed to preserve things like
`FirImplicitAnyTypeRef`. For an example, see:
`FirOldFrontendMPPDiagnosticsWithPsiTestGenerated.testExpectAnnotationAndInlineClassWithDefaultValue`.

We should also jump to typealiases in supertypes of class-like types. We
need to make sure that by the time we want to fully expand typealiases in
supertypes we already have analyzed them. Currently, we only transitively
analyze typealiases within other typealiases (see `visitTypeAlias()`) and
check all supertypes of outer classes via
`resolveAllSupertypesForOuterClass(outerClass)`).

The change in `FirSupertypesResolution` is also backed by:

- `JvmIrInterpreterAfterFirPsi2IrTestGenerated.testAbstract1`:
  - `unable to fully expand `RandomAccess` (coming from
  `libraries/stdlib/jvm/src/kotlin/collections/TypeAliases.kt`)
  typealias in supertypes of `EmptyList` (coming from
  `compiler/testData/ir/interpreter/helpers/Collections.kt`), because of
  what seems to be the files order.

Without the change in LL, IDE runners like
`LLFirPreresolvedReversedDiagnosticCompilerFirTestDataTestGenerated` and
`DiagnosticCompilerTestFirTestdataTestGenerated` will produce
conflicting changes into the test data files. For a specific example:
consider `DiagnosticCompilerTestFirTestdataTestGenerated.Resolve`
`.Multifile#testTypeAliasExpansion`.

Recursive expansion in LL is needed, because otherwise we can't call
`fullyExpandedType()` as it wont have all the needed data.

Note that `typeAlias.expandedConeType` returns `null` if the typealias
expands to something incorrect, like its own type parameter. In this
case, it's already resolved, so we don't need to look up anything in the
session.

This change is also backed by:
`LLFirPreresolvedReversedDiagnosticCompilerFE10TestDataTestGenerated`
`.Tests.Typealias#testTypeAliasShouldExpandToClass`. Otherwise:

> java.lang.IllegalArgumentException: Unexpected status at
> FirApplySupertypesTransformer: org.jetbrains.kotlin.fir.resolve.transformers
> .SupertypeComputationStatus$NotComputed@3839fdcb for
> /Outer.ToTypeParam1

...because non-recursive expansion of a typealias pointing to
`Outer.ToTypeParam1` leads to our inability to fully expand
`Outer.toTypeParam1`.

Note: in this case, since `Outer.ToTypeParam1<T>` expands to `T`, which
is a type parameter, not a `ConeClassLikeType`, the typealias can't have
a meaningful `fullyExpandedType()`, so calling `fullyExpandedType()` for
`Outer.ToTypeParam4 = Outer.ToTypeParam1<Any>` still returns
`Outer.ToTypeParam1<Any>`, not `T`. This is fine, because in any case
`Outer.ToTypeParam1<T> = T` is red code.