[TEST] expect-actual. Reproduce partial linkage error in Wasm, JS, native
Reproduce KT-71817
JVM is not affected
Caused by: 2bbc1e7ef75c9874ce9438155ee1364a3a785781

    There are linkage errors reported by the partial linkage engine
    org.jetbrains.kotlin.analyzer.CompilationErrorException: There are linkage errors reported by the partial linkage engine
            at org.jetbrains.kotlin.backend.common.linkage.issues.KotlinIrLinkerIssue.raiseIssue(KotlinIrLinkerIssues.kt:29)
            at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl.generateStubsAndPatchUsagesInternal(PartialLinkageSupportForLinkerImpl.kt:88)
            at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl.generateStubsAndPatchUsages(PartialLinkageSupportForLinkerImpl.kt:62)
            at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.postProcess(KotlinIrLinker.kt:223)
            at org.jetbrains.kotlin.ir.backend.js.KlibKt.getIrModuleInfoForKlib(klib.kt:274)
            at org.jetbrains.kotlin.ir.backend.js.KlibKt.loadIr(klib.kt:213)
            at org.jetbrains.kotlin.ir.backend.js.KlibKt.loadIr$default(klib.kt:168)