IJ SDK: Adjust CoreProgressManager.java to avoid loading IJ coroutines
Platform now uses a custom fork of kotlinx.coroutines:
https://github.com/JetBrains/intellij-deps-kotlinx.coroutines

It has kotlinx/coroutines/internal/intellij/IntellijCoroutine
which the original library doesn't contain.

On the other hand, loading the class is only triggered in a few
places, mostly from CoreProgressManager, so we replace them for now:
- doCheckCanceled just does nothing as it's expected in CLI
- computeInNonCancelableSection does run the task just in the current
thread, which seems reasonable in a single-thread environment as well.

After IJPL-207644 has been fixed, since 253 we can hopefully remove
the workaround, via setting
`ide.can.use.coroutines.fork` property to false.

Otherwise, many tests start failing like ResolveDependenciesTest

Caused by: java.lang.NoClassDefFoundError: kotlinx/coroutines/internal/intellij/IntellijCoroutines
  at com.intellij.concurrency.ThreadContext.installThreadContext$lambda$8(threadContext.kt:291)
  at com.intellij.concurrency.ThreadContext.withThreadLocal(threadContext.kt:353)
  at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:289)
  at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:137)
  at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:297)
  at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:288)
  at com.intellij.psi.impl.source.tree.LazyParseableElement.setChildren(LazyParseableElement.java:212)
  at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$2(LazyParseableElement.java:187)
  at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:548)
  at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:182)
  at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:234)
  at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:25)
  at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:37)
  at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:850)
  at com.intellij.psi.util.PsiTreeUtil.getChildrenOfTypeAsList(PsiTreeUtil.java:413)
  at org.jetbrains.kotlin.psi.KtCommonFile.getDeclarations(KtCommonFile.kt:146)
  at org.jetbrains.kotlin.scripting.compiler.plugin.impl.JvmCompilationUtilKt.getScriptKtFile(jvmCompilationUtil.kt:95)