[Build] Add `:compiler:arguments.common` to `kotlinJpsPluginEmbeddedDependencies`
To fix `NoClassDefFoundError` (org/jetbrains/kotlin/cli/common/arguments/Enables)
for projects where JPS plugin is used (IntelliJ monorepo)