[K/N] Use the name of the class in NoClassDefFoundError
If the class has failed to initialize due to an exception in its static
initializer, use the class's name in the thrown `NoClassDefFoundError`.
This makes the exception message consistent with Kotlin/JVM.

KT-57134