[TEST] expect-actual. Reproduce partial linkage error in Wasm, JS, native
Reproduce KT-71817
Caused by: 2bbc1e7ef75c9874ce9438155ee1364a3a785781

There are two errors:

    There are linkage errors reported by the partial linkage engine
    org.jetbrains.kotlin.analyzer.CompilationErrorException: There are linkage errors reported by the partial linkage engine
            at org.jetbrains.kotlin.backend.common.linkage.issues.KotlinIrLinkerIssue.raiseIssue(KotlinIrLinkerIssues.kt:29)
            at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl.generateStubsAndPatchUsagesInternal(PartialLinkageSupportForLinkerImpl.kt:88)
            at org.jetbrains.kotlin.backend.common.linkage.partial.PartialLinkageSupportForLinkerImpl.generateStubsAndPatchUsages(PartialLinkageSupportForLinkerImpl.kt:62)
            at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.postProcess(KotlinIrLinker.kt:223)
            at org.jetbrains.kotlin.ir.backend.js.KlibKt.getIrModuleInfoForKlib(klib.kt:274)
            at org.jetbrains.kotlin.ir.backend.js.KlibKt.loadIr(klib.kt:213)
            at org.jetbrains.kotlin.ir.backend.js.KlibKt.loadIr$default(klib.kt:168)

and

    Somewhere in file /platform.kt: java.lang.IllegalArgumentException: This function should be invoked only for declarations in the same kind of container (both members or both top level): FirNamedFunctionSymbol /E.values, FirNamedFunctionSymbol /E.values
    org.jetbrains.kotlin.util.FileAnalysisException: Somewhere in file /platform.kt: java.lang.IllegalArgumentException: This function should be invoked only for declarations in the same kind of container (both members or both top level): FirNamedFunctionSymbol /E.values, FirNamedFunctionSymbol /E.values
            at org.jetbrains.kotlin.util.AnalysisExceptionsKt.wrapIntoFileAnalysisExceptionIfNeeded(AnalysisExceptions.kt:62)
            at org.jetbrains.kotlin.fir.FirCliExceptionHandler.handleExceptionOnFileAnalysis(Utils.kt:249)
            at org.jetbrains.kotlin.fir.resolve.transformers.FirAbstractPhaseTransformer.transformFile(FirAbstractPhaseTransformer.kt:45)
            at org.jetbrains.kotlin.fir.declarations.FirFile.transform(FirFile.kt:46)
            at org.jetbrains.kotlin.fir.resolve.transformers.FirTransformerBasedResolveProcessor.processFile(FirResolveProcessor.kt:48)
            at org.jetbrains.kotlin.fir.resolve.transformers.mpp.FirExpectActualMatcherProcessor.processFile(FirExpectActualMatcherTransformer.kt:31)
            at org.jetbrains.kotlin.fir.resolve.transformers.FirTotalResolveProcessor.process(FirTotalResolveProcessor.kt:36)

The first one is applicable only to non-JVM backends. The second one is
applicable to all backends.