[Tests] Ensure `javac` is instructed to use the proper encoding
Otherwise, sometimes it uses a different one, so running
some tests like
`org.jetbrains.kotlin.test.runners.ForeignAnnotationsSourceJavaTestGenerated.Java11Tests.JspecifyOld.ModuleAnnotations.Warn#testComposeWithClassDefaultAnnotation`
results in "Java files are not compiled successfully",
because it tries to compile a file (for example,
`third-party/java9-annotations/org/jspecify/annotations/NonNull.java`)
containing a comment that includes a character like "…"
resulting in `javac` complaining:

> NonNull.java:55: error: unmappable character (0xE2) for encoding US-ASCII
> * class MyOptional<T> { ??? }

Thanks @semoro for this fix!