Run jklib tests using the real JDK 17 rather than MOCK_JDK
Otherwise, tests like `FirJKlibIrTextTestGenerated.Singletons.testObject`
fail with:

```
Module "kotlin-stdlib" has a reference to symbol java.lang/Enum.EnumDesc|null[0]. Neither the module itself nor its dependencies contain such declaration.

This could happen if the required dependency is missing in the project. Or if there is a dependency of "kotlin-stdlib" that has a different version in the project than the version that "kotlin-stdlib" was initially compiled with. Please check that the project configuration is correct and has consistent versions of all required dependencies.
org.jetbrains.kotlin.analyzer.CompilationErrorException: Module "kotlin-stdlib" has a reference to symbol java.lang/Enum.EnumDesc|null[0]. Neither the module itself nor its dependencies contain such declaration.
```

The mock JDK is based off of JDK 8, and has no `EnumDesc`.

^KT-88173

(cherry picked from commit b2af0ddd27515eb3ddb6411f93b7476b6ecc2ca0)