[CLI] Check for VirtualMachineError in `FirCliExceptionHandler`
If exception was caused by lack of static memory (e.g.
`StackOverflowError`), the memory would be not sufficient to load the
`AnalysisExceptionsKt.class` containing the `wrapIntoSourceCodeAnalysisExceptionIfNeeded`
utility, which would lead to overriding the original exception with
`NoClassDefFoundError`. So, considering that `wrapIntoSourceCodeAnalysisExceptionIfNeeded`
skips VM errors anyway, is's ok to check for it earlier.

^KT-88026 Fixed