[stdlib] Delete recently introduced exceptions from common & JVM parts
- `ExceptionInInitializerError` was introduced in
  5959617b4f9bbec18220ff94f922e6aa87410381
- `NoClassDefFoundError` was introduced in
  5546a55fb1d5743a9e76fb77a6ff05409696064d

Both classes were introduced in the scope of KT-57134.
We only need them on non-JVM targets.
We also introduced `expect` counterparts in the common source set, and
two type aliases on the JVM source set, just to be clear that they
are related.

However, because Kotlin auto-imports `java.lang.*` (where both these
classes reside on JVM) with lower priority than other auto-imports,
a usage of `NoClassDefFoundError` in user code started being resolved
to the newly introduced type alias. The problem is that this type alias
has internal visibility, causing `INVISIBLE_REFERENCE` compilation
errors.

For this reason, we remove the declarations from the common and JVM
source sets — they weren't needed there anyway.